# Generated by Django 2.1.5 on 2019-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20190831_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usern', models.CharField(max_length=100)),
                ('emailadd', models.CharField(max_length=400)),
                ('passw', models.CharField(max_length=100)),
                ('passwr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
