# Generated by Django 2.1.5 on 2019-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='webimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagex', models.ImageField(upload_to='Images/')),
            ],
            options={
                'db_table': 'webimages',
            },
        ),
    ]
